<script>
selectedResource.isLinkedData = false;
var standardPublishHubUrl = '<?php echo $this->standardPublishHubUrl; ?>';
var standardHubUrl = '<?php echo $this->standardHubUrl; ?>';
var callbackUrl = '<?php echo $this->callbackUrl; ?>';
var topicUrl = '<?php echo false === $this->topicUrl ? '' : $this->topicUrl; ?>';
var headerFeedTags = '<?php echo json_encode($this->headerFeedTags); ?>';
var resourceInformation = '';
headerFeedTags = jQuery.parseJSON(headerFeedTags);

$(document).ready(function(){
    $("#pubsub-subscriptions-msgBoxNewFeedUpdates").hide();
    $('#subscriptions').hide();
    
    /**
     * You are ALREADY subscribed to the given resource
     * So the topic url is already in the store
     */
    if ('' != topicUrl)
    {
        /**
         * Set events
         */
        $('#pubsub-subscriptions-msgBoxLinkedData').fadeIn('slow');
        $('#subscriptions').fadeIn('slow');
        
        $('#pubsub-subscriptions-msgBoxFeedSubscribed').fadeIn('slow');
        $('#pubsub-subscriptions-buttonSubscribe').click(function(){
            subscribe(topicUrl, 'subscribe');
        });
        $('#pubsub-subscriptions-buttonUnSubscribe').click(function(){
            subscribe(topicUrl, 'unsubscribe');
        });
        
        // check if there are feed updates for the given topic url
        checkForFeedUpdates(
            selectedResource.URI, 
            function(data){            
                // If there are new feed updates (related files in cache folder)
                if("true" == data) {
                    $("#pubsub-subscriptions-msgBoxNewFeedUpdates").fadeIn("slow");
                    
                    /**
                     * Set click event for button to import feed updates
                     */
                    $('#pubsub-subscriptions-buttonImportFeedUpdates').click(function(){
                        importFeedUpdates(selectedResource.URI);
                    });
                }
        });
    }
    
    /**
     * You are NOT subscribed to the given resource!
     */
    else
    {
        checkResource(
            selectedResource.URI, 
            function(data) {
                
                // result data >> JSON
                resourceInformation = $.parseJSON(data);
                
                // show isLinkedData box if resource is linked data
                if (true == resourceInformation.isLinkedData)
                {
                    $('#subscriptions').fadeIn('slow');
                    $('#pubsub-subscriptions-msgBoxLinkedData').fadeIn('slow');
                }
                
                $.ajax({
                    url: urlBase + 'resource/head/',
                    data: {r : selectedResource.URI, noredirect: false}
                }).error(function ( xhr ) {
                    console.log(xhr);
                }).done(function ( data, textStatus, jqXHR ) {
                }).success(function ( data, textStatus, jqXHR ) {
                    data = $.parseJSON(data);
                    data = arrayKeysToUpper(data);
                    if (undefined !== data[headerFeedTags[0]])
                    {
                        var subscriptionTopicUrl = data[headerFeedTags[0]];
                        $.ajax({
                            url: subscriptionTopicUrl,
                            datatype: 'xml'
                        }).error(function ( xhr ) {
                            console.log(xhr);
                        }).success(function ( data, textStatus, jqXHR ) {
                            $('#subscriptions').fadeIn('slow');
                            $('#pubsub-subscriptions-msgBoxLinkedDataAndFeed').fadeIn('slow');
                            $('#pubsub-subscriptions-buttonSubscribe').click(function(){
                                subscribe(subscriptionTopicUrl, 'subscribe');
                            });
                            $('#pubsub-subscriptions-buttonUnSubscribe').click(function(){
                                subscribe(subscriptionTopicUrl, 'unsubscribe');
                            });
                            if (false == resourceInformation.isLinkedData && true == resourceInformation.isLocalResource)
                            {
                                $('#pubsub-subscriptions-msgBoxPublish').fadeIn('slow');
                                $('#pubsub-subscriptions-buttonPublish').click(function(){
                                    $.ajax({
                                        url: urlBase + 'pubsub/publish/',
                                        data: {
                                            hubUrl : standardPublishHubUrl,
                                            topicUrl : subscriptionTopicUrl
                                        },
                                        dataType: 'JSON'
                                    }).error(function ( xhr ) {
                                        console.log(xhr);
                                    }).success(function ( data, textStatus, jqXHR ) {
                                        $('#pubsub-subscriptions-msgBoxPublish').fadeOut('slow');
                                    });
                                });
                            }
                        });
                    }
                });
            }
        );
    }
});

/**
 * FUNCTIONS
 */
 
// 
function arrayKeysToUpper(data) {
    for ( var index in data) {
        data[index.toLowerCase()] = data[index];
    }
    return data;
}
 
// check the feed for new updates
function checkForFeedUpdates(selectedResourceUri, callback) {
    // check if there are feed updates for the given topic url
    $.ajax({
        url: urlBase + 'pubsub/existsfeedupdates/',
        data: {r : selectedResourceUri}
    }).error(function ( xhr ) {
    }).done(function ( data, textStatus, jqXHR ) {
    }).success(function ( data, textStatus, jqXHR ){
        callback(data);
    });
}

// 
function checkResource(selectedResourceUri, callback) {
    $.ajax({
        url: urlBase + 'pubsub/checkresource/',
        datatype: 'JSON',
        data: {r : selectedResource.URI}
    }).error(function ( xhr ) {
    }).done(function ( data, textStatus, jqXHR ) {
    }).success(function ( data, textStatus, jqXHR ) {
        callback(data);
    });
}

// import feed updates for the given selected resource uri
function importFeedUpdates(selectedResourceUri) {
    $.ajax({
        url: urlBase + 'pubsub/importfeedupdates/',
        data: {r : selectedResourceUri},
        dataType: 'JSON'
    }).error(function ( xhr ) {
    }).done(function ( data, textStatus, jqXHR ) {
    }).success(function ( data, textStatus, jqXHR ){
        if ("true" === data) {
            $("#pubsub-subscriptions-msgBoxNewFeedUpdates").fadeOut("slow");
            location.reload();
        }
    });
}

//
function subscribe(topicUrl, mode) {
    $.ajax({
        url: urlBase + 'pubsub/subscription',
        data:{
            hubUrl : standardHubUrl,
            topicUrl : topicUrl,
            callBackUrl : callbackUrl,
            subscriptionMode : mode,
            verifyMode : 'sync',
            sourceResource : selectedResource.URI
        }
    }).error(function ( xhr ) {
        console.log(xhr);
    }).success(function ( data, textStatus, jqXHR ) {
        if ('subscribe' == mode)
        {
            $('#pubsub-subscriptions-msgBoxLinkedDataAndFeed').fadeOut('slow', function() {
                $('#pubsub-subscriptions-msgBoxFeedSubscribed').fadeIn('slow');
            });
        }
        else
        {
            $('#pubsub-subscriptions-msgBoxFeedSubscribed').fadeOut('slow', function() {
                $('#pubsub-subscriptions-msgBoxLinkedDataAndFeed').fadeIn('slow');
            });
        }
        //console.log(data);
    }).done(function ( data, textStatus, jqXHR ) {
    });
}

</script>

<!-- If this resource is not a local resource and feed + attached hub exists on it -->
<div class="has-contextmenu-area" style="display:none;" id="pubsub-subscriptions-msgBoxLinkedData">
    <div class="contextmenu">
        <a class="item fetch_data_button wrapper_linkeddata Resource" about="<?php echo $this->selectedResourceUri; ?>">
            <span class="icon icon-save" title="Pull and Save">
                <span>Pull and Save</span>
            </span>
        </a>
    </div>
    <div class="messagebox search">
        This resource is available as Linked Data, so <strong>you can pull and save</strong>
        the current version of this resource.
    </div>
</div>

<!-- If this resource is not a local resource and feed + attached hub exists on it -->
<div class="has-contextmenu-area" style="display:none;" id="pubsub-subscriptions-msgBoxLinkedDataAndFeed">
    <div class="contextmenu">
        <a class="item" id="pubsub-subscriptions-buttonSubscribe">
            <span class="icon icon-toggle-on" title="Add Updates Subsciption">
                <span>Add Updates Subsciption</span>
            </span>
        </a>
    </div>
    <div class="messagebox feed">
        This resource is available as Linked Data and has an attached subscription feed,
        so <strong>you can subscribe to any updates</strong> from the maintainer of
        this resource.
    </div>
</div>

<!-- If this resource is not a local resource and a subscription to it already exists -->
<div class="has-contextmenu-area" style="display:none;" id="pubsub-subscriptions-msgBoxFeedSubscribed">
    <div class="contextmenu">
        <a class="item" id="pubsub-subscriptions-buttonUnSubscribe">
            <span class="icon icon-toggle-off" title="Cancel Updates Subscription">
                <span>Cancel Updates Subscription</span>
            </span>
        </a>
    </div>
    <div class="messagebox info">
        <strong>You are subscribed</strong> to any updates of this resource.</strong>.
    </div>
</div>

<!-- If this resource is not a local resource and a subscription to it already exists -->
<div class="has-contextmenu-area" style="display:none;" id="pubsub-subscriptions-msgBoxNewFeedUpdates">
    <div class="contextmenu">
        <a class="item" id="pubsub-subscriptions-buttonImportFeedUpdates">
            <span class="icon icon-toggle-off" title="Import updates">
                <span>Import updates</span>
            </span>
        </a>
    </div>
    <div class="messagebox success">
        <strong>There are new updates for this resource!</strong>.
    </div>
</div>

<!-- If this resource is a local resource then it can be published -->
<div class="has-contextmenu-area" style="display:none;" id="pubsub-subscriptions-msgBoxPublish">
    <div class="contextmenu">
        <a class="item" id="pubsub-subscriptions-buttonPublish">
            <span class="icon icon-toggle-off" title="Publish">
                <span>Publish</span>
            </span>
        </a>
    </div>
    <div class="messagebox info">
        <strong>Publish resource updates</strong>.
    </div>
</div>

<!-- If this resource IS a local resource and linked data enabled  -->
<div class="has-contextmenu-area" style="display:none;">
    <div class="contextmenu">
        <a class="item">
            <span class="icon icon-cancel" title="Cancel Subscriptions">
                <span>Cancel Subscribers</span>
            </span>
        </a>
        <a class="item">
            <span class="icon icon-list" title="List Subscribers">
                <span>List Subscribers</span>
            </span>
        </a>
    </div>
    <div class="messagebox info">
        There are currently <strong>5 subscribers</strong> to this resource
        which receive your changes.
    </div>
</div>



