<script>
    selectedResource.isLinkedData = false;
    var standardHubUrl = '<?php echo $this->standardHubUrl; ?>';
    var callbackUrl = '<?php echo $this->callbackUrl; ?>';
    var topicUrl = '<?php echo false === $this->topicUrl ? '' : $this->topicUrl; ?>';
    var headerFeedTags = '<?php echo json_encode($this->headerFeedTags); ?>';
    headerFeedTags = jQuery.parseJSON(headerFeedTags);

    $(document).ready(function(){
        $('#subscriptions').hide();
        if ('' != topicUrl)
        {
            $('#pubsub-subscriptions-msgBoxFeedSubscribed').fadeIn('slow');
            $('#pubsub-subscriptions-buttonSubscribe').click(function(){
                subscribe(topicUrl, 'subscribe');
            });
            $('#pubsub-subscriptions-buttonUnSubscribe').click(function(){
                subscribe(topicUrl, 'unsubscribe');
            });
        }
        else
        {
            $.ajax({
                url: urlBase + 'pubsub/islinkeddata/',
                datatype: 'JSON',
                data: {r : selectedResource.URI}
            }).error(function ( xhr ) {
            }).done(function ( data, textStatus, jqXHR ) {
            }).success(function ( data, textStatus, jqXHR ) {
                if (true == $.parseJSON(data))
                {
                    $('#pubsub-subscriptions-msgBoxLinkedData').fadeIn('slow');
                    $('#subscriptions').fadeIn('slow');
                    $.ajax({
                        url: urlBase + 'resource/head/',
                        data: {r : selectedResource.URI, noredirect: true}
                    }).error(function ( xhr ) {
                        console.log(xhr);
                    }).done(function ( data, textStatus, jqXHR ) {
                    }).success(function ( data, textStatus, jqXHR ) {
                        data = $.parseJSON(data);
                        $.ajax({
                            url: data[headerFeedTags[0]],
                            type: 'xml'
                        }).error(function ( xhr ) {
                            console.log(xhr);
                        }).success(function ( data, textStatus, jqXHR ) {
                            $('#pubsub-subscriptions-msgBoxLinkedDataAndFeed').fadeIn('slow');
                            $('#pubsub-subscriptions-buttonSubscribe').click(function(){
                                subscribe(data.baseURI, 'subscribe');
                            });
                            $('#pubsub-subscriptions-buttonUnSubscribe').click(function(){
                                subscribe(data.baseURI, 'unsubscribe');
                            });
                        });
                    });
                }
            });
        }
    });
    
   
function subscribe(topicUrl, mode) {
    $.ajax({
        url: urlBase + 'pubsub/subscription',
        data:{
            hubUrl : standardHubUrl,
            topicUrl : topicUrl,
            callBackUrl : callbackUrl,
            subscriptionMode : mode,
            verifyMode : 'sync',
            sourceResource : selectedResource.URI
        }
    }).error(function ( xhr ) {
        console.log(xhr);
    }).success(function ( data, textStatus, jqXHR ) {
        if ('subscribe' == mode)
        {
            $('#pubsub-subscriptions-msgBoxLinkedDataAndFeed').fadeOut('slow', function() {
                $('#pubsub-subscriptions-msgBoxFeedSubscribed').fadeIn('slow');
            });
        }
        else
        {
            $('#pubsub-subscriptions-msgBoxFeedSubscribed').fadeOut('slow', function() {
                $('#pubsub-subscriptions-msgBoxLinkedDataAndFeed').fadeIn('slow');
            });
        }
        //console.log(data);
    }).done(function ( data, textStatus, jqXHR ) {
    });
}

</script>

<!-- If this resource is not a local resource and feed + attached hub exists on it -->
<div class="has-contextmenu-area" style="display:none;" id="pubsub-subscriptions-msgBoxLinkedData">
    <div class="contextmenu">
        <a class="item fetch_data_button wrapper_linkeddata Resource" about="<?php echo $this->selectedResourceUri; ?>">
            <span class="icon icon-save" title="Pull and Save">
                <span>Pull and Save</span>
            </span>
        </a>
    </div>
    <div class="messagebox search">
        This resource is available as Linked Data, so <strong>you can pull and save</strong>
        the current version of this resource.
    </div>
</div>

<!-- If this resource is not a local resource and feed + attached hub exists on it -->
<div class="has-contextmenu-area" style="display:none;" id="pubsub-subscriptions-msgBoxLinkedDataAndFeed">
    <div class="contextmenu">
        <a class="item" id="pubsub-subscriptions-buttonSubscribe">
            <span class="icon icon-toggle-on" title="Add Updates Subsciption">
                <span>Add Updates Subsciption</span>
            </span>
        </a>
    </div>
    <div class="messagebox feed">
        This resource is available as Linked Data and has an attached subscription feed,
        so <strong>you can subscribe to any updates</strong> from the maintainer of
        this resource.
    </div>
</div>

<!-- If this resource is not a local resource and a subscription to it already exists -->
<div class="has-contextmenu-area" style="display:none;" id="pubsub-subscriptions-msgBoxFeedSubscribed">
    <div class="contextmenu">
        <a class="item" id="pubsub-subscriptions-buttonUnSubscribe">
            <span class="icon icon-toggle-off" title="Cancel Updates Subscription">
                <span>Cancel Updates Subscription</span>
            </span>
        </a>
    </div>
    <div class="messagebox success">
        <strong>You are subscribed</strong> to any updates of this resource.
        The last update was pushed approx. <strong>10 minutes ago</strong>.
    </div>
</div>

<!-- If this resource IS a local resource and linked data enabled  -->
<div class="has-contextmenu-area" style="display:none;">
    <div class="contextmenu">
        <a class="item">
            <span class="icon icon-cancel" title="Cancel Subscriptions">
                <span>Cancel Subscribers</span>
            </span>
        </a>
        <a class="item">
            <span class="icon icon-list" title="List Subscribers">
                <span>List Subscribers</span>
            </span>
        </a>
    </div>
    <div class="messagebox info">
        There are currently <strong>5 subscribers</strong> to this resource
        which receive your changes.
    </div>
</div>



