<!-- If this resource is not a local resource and feed + attached hub exists on it -->
<div class="has-contextmenu-area">
    <div class="contextmenu">
        <a class="item">
            <span class="icon icon-save" title="Pull and Save">
                <span>Pull and Save</span>
            </span>
        </a>
    </div>
    <div class="messagebox search">
        This resource is available as Linked Data, so <strong>you can pull and save</strong>
        the current version of this resource.
    </div>
</div>

<!-- If this resource is not a local resource and feed + attached hub exists on it -->
<div class="has-contextmenu-area">
    <div class="contextmenu">
        <a class="item">
            <span class="icon icon-toggle-on" title="Add Updates Subsciption">
                <span>Add Updates Subsciption</span>
            </span>
        </a>
    </div>
    <div class="messagebox feed">
        This resource is available as Linked Data and has an attached subscription feed,
        so <strong>you can subscribe to any updates</strong> from the maintainer of
        this resource.
    </div>
</div>

<!-- If this resource is not a local resource and a subscription to it already exists -->
<div class="has-contextmenu-area">
    <div class="contextmenu">
        <a class="item">
            <span class="icon icon-toggle-off" title="Cancel Updates Subscription">
                <span>Cancel Updates Subscription</span>
            </span>
        </a>
    </div>
    <div class="messagebox success">
        <strong>You are subscribed</strong> to any updates of this resource.
        The last update was pushed approx. <strong>10 minutes ago</strong>.
    </div>
</div>

<!-- If this resource IS a local resource and linked data enabled  -->
<div class="has-contextmenu-area">
    <div class="contextmenu">
        <a class="item">
            <span class="icon icon-cancel" title="Cancel Subscriptions">
                <span>Cancel Subscribers</span>
            </span>
        </a>
        <a class="item">
            <span class="icon icon-list" title="List Subscribers">
                <span>List Subscribers</span>
            </span>
        </a>
    </div>
    <div class="messagebox info">
        There are currently <strong>5 subscribers</strong> to this resource
        which receive your changes.
    </div>
</div>



