<!-- If this model contains at least one resource which has feed updates. -->
<div class="has-contextmenu-area" id="pubsub-modeloverview-msgBoxNewFeedUpdates">
    <div class="contextmenu">
        <a class="item" id="pubsub-modeloverview-buttonImportFeedUpdates">
            <span class="icon icon-toggle-on" title="Import updates">
                <span>Import updates</span>
            </span>
        </a>
    </div>
    <div class="messagebox success">
        There are <strong>new feed updates</strong> for at least one resource in this model.
    </div>
</div>

<!-- After feed updates were imported -->
<div class="has-contextmenu-area" style="display:none;" id="pubsub-modeloverview-msgBoxFeedUpdatesImported">
    <div class="messagebox info">
        Feed updates were successfully imported.
    </div>
</div>
